/** 
 * GET POKEMONS ACTIONS CONSTANTS
 */
export const GET_ALL_POKEMONS =  'GET_ALL_POKEMONS';
export const GET_ALL_POKEMON_SUCCESS =  'GET_ALL_POKEMON_SUCCESS';
export const GET_ALL_POKEMON_ERROR =  'GET_ALL_POKEMON_ERROR';

/**
 * UPDATE POKEMON ACTION CONSTANTS
 */
export const UPDATE_POKEMON =  'UPDATE_POKEMON';
export const UPDATE_POKEMON_SUCCESS =  'UPDATE_POKEMON_SUCCESS';
export const UPDATE_POKEMON_ERROR =  'UPDATE_POKEMON_ERROR';

/**
 * SEARCH POKEMON CONSTANTS
 */
export const SEARCH_POKEMONS =  'SEARCH_POKEMONS';
export const SEARCH_END = "SEARCH_END";
export const RESET_SEARCH_STRING = "RESET_SEARCH_STRING";
export const SEARCH_ERROR = "SEARCH_ERROR";